name: Build and Deploy User Service

on:
  push:
    branches:
      - master  # Menjalankan workflow ketika ada perubahan di branch main
  pull_request:
    branches:
      - master  # Menjalankan workflow ketika ada pull request ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image for User Service
        run: |
          ls -l
          docker build -t user-service .

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag user-service pridenous/user-service:latest
          docker push pridenous/user-service

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Menunggu job sebelumnya selesai sebelum menjalankan deployment

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Pull dan Restart Container di VPS
        run: |
      - name: Pull dan Restart Container di VPS
        run: |
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull pridenous/user-service:latest
          docker stop app_container || true
          docker rm app_container || true
          docker run -d --name app_container -p 80:80 pridenous/user-service:latest
EOF

