name: Build and Deploy User Service

on:
  push:
    branches:
      - master  # Menjalankan workflow ketika ada perubahan di branch main
  pull_request:
    branches:
      - master  # Menjalankan workflow ketika ada pull request ke branch main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image for User Service
        run: |
          ls -l
          docker build -t user-service .

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag user-service pridenous/user-service:latest
          docker push pridenous/user-service

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}  # Tambahkan port SSH di sini
          script: |
            echo "Pulling latest Docker image..."
            docker pull pridenous/user-service:latest

            echo "Stopping old container..."
            docker stop user-service || true
            docker rm user-service || true

            echo "Running new container..."
            docker run -d --name user-service -p 80:80 pridenous/user-service:latest
