name: Build and Deploy User Service

on:
  push:
    branches:
      - master  # Menjalankan workflow ketika ada perubahan di branch main
  pull_request:
    branches:
      - master  # Menjalankan workflow ketika ada pull request ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/cache@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image for User Service
        run: |
          cd user-service
          docker build -t user-service .

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag userservice mydockerhubuser/userservice:latest
          docker push mydockerhubuser/userservice:latest
